osism/cloud-in-a-box

README.md

A few more words on:
* wireguard-client.conf
* Pointer to testbed docu
* homer dashboard
As soon as we have a more comprehensive CiaB getting started guide, we would link that of course. For now, this seems useful to save research to get going.
Signed-off-by: Kurt Garloff <kurt@garloff.de>

Getting started on the Cloud-in-a-Box.

---

environments/kolla/files/overlays/nova.conf

The default value in the nova.conf template should be good enough.
Part of osism/cloud-in-a-box#20

kolla: remove novncproxy_base_url

---

prepare.sh

This script sets the correct interface name in the /opt/configuration directory.

Add prepare.sh script

---

environments/kolla/configuration.yml

This can be reverted after fixing in the ansible-default repository

Add neccessary variable for nova

---

bootstrap.sh
environments/manager/configuration.yml
environments/manager/secrets.yml

After a restart some container have problems to coming up in fact that them are waiting for netbox.
These containers are staying in restarting:
manager-api-1
manager-openstack-1
manager-listener-1
Reverts osism/cloud-in-a-box#47

Revert "manager: disable netbox service"

---

environments/manager/images.yml

MANAGER_VERSION=4.2.0 gilt overlay
The Netbox version was wrong. A sync against cfg-generics with the corresponding manager version solves the problem and brings environments/manager to the correct state.

Sync with cfg-generics

---

deploy.sh
environments/openstack/playbook-bootstrap-images.yml

This way it is possible to also manage the images on older manager versions.

openstack: add bootstrap-images playbook

---

environments/openstack/playbook-bootstrap.yml
inventory/group_vars/generic/network.yml
network/iptables.sh
network/vxlan.sh

The management interface instead of the internal interface has to be masqueraded.
Closes osism/cloud-in-a-box#17

Fix masquerading

---

quickstart.md

If we want to implement the documentation at scs side we have to change
the name of the README.md.
I did some code correctures to make the boxes with warnings and notes more
visibel at docusaurus.

Preparation for pubblishing the documentation

---

deploy.sh
environments/infrastructure/configuration.yml

The wireguard role has been refactored, adapt the configuration to the new parameters. Use the same key as within the testbed for consistency.

Adapt wireguard configuration

---

environments/manager/configuration.yml

Has been disabled by default in OSISM 5.

manager: enable flower service

---

environments/manager/configuration.yml

mariadb is a faster backend than sqlite.

manager: use mariadb as ara backend

---

environments/manager/configuration.yml

closes #89 
Wrong branch for configuration used
Signed-off-by: Tim Beermann <beermann@osism.tech>

closes #89

---

environments/ceph/configuration.yml

Since we have only one node we have to take the OSDs as failure domain.

ceph: set osd crush chooseleaf type = 0

---

deploy.sh

The play requires a usable Keystone service.

Bootstrap Ceph RGW after the Keystone deployment

---

deploy.sh

Looks like this is not longer required after the change of the failure domain from hosts to devices.

Remove ceph workaround with device_health_metrics

---

.gitignore
bootstrap.sh
deploy.sh
include.sh
prepare.sh
releasenotes/notes/improve-nic-handling-369df0b6e38e8c6b.yaml
releasenotes/notes/refactor-ciab-installation-e2341960ba39e618.yaml
upgrade.sh

- wait for a working uplink in bootstrap.sh and deploy.sh
- add a funcionality to log the entire output to a logfile
(for debugging purposes)
- improve the runtime of the interface
replacement from ~70sec to ~6.5sec
- discover the interface by analyzing the default routes (`ip route ls`), take the first default route
- refactoring: move common functions to include.sh

Improvements for the bootstrap procedure

---

deploy.sh

Not longer required, fixed playbook is part of OSISM 6.0.2.

Remove ceph dashboard bootstrap workaround

---

environments/infrastructure/configuration.yml

Required because the Horizon service is also running on port 443.

Change traefik https port from 443 to 10443

---

environments/openstack/playbook-test.yml

Related to osism/testbed/#2031

openstack: in the test play do not build port in advance

---

bootstrap.sh
environments/kolla/configuration.yml

To avoid confusion and due to the limited resources we have, only OVN is now supported as a backend for Octavia.

kolla: only use OVN for octavia

---

environments/infrastructure/configuration.yml
environments/kolla/configuration.yml

By moving Horizon to port 1080 and Traefik back to the standard ports, everything is as it should be.
Related to 9d3ecddf087dfd541d066dc143f62f6a9259a727

Make all DNS records usable again

---

environments/infrastructure/configuration.yml
environments/manager/configuration.yml

By moving the Netbox service between the environments, all parameters must currently be present in both environments.

Prepare Netbox configuration for OSISM 7

---

deploy.sh
upgrade.sh

As the deployment of Ironic has been prepared so far, but will only be deployed later in a manual step, the service is deactivated here for the moment.

Disable the ironic-neutron-agent service after deployment/upgrade

---

deploy.sh
init.sh

In this way, in addition to the kernel parameters, additional parameters can also be transferred via the cloud init file when the init.sh script is called.
Furthermore, it is now ensured that a valid type is also used.

Add support for extra params in the init.sh script

---

bootstrap.sh
deploy.sh
prepare-clusterapi.sh
prepare.sh
upgrade-manager.sh
upgrade.sh

If CIAB install fails, you are getting currently also the tracing output of the add_error function.
```
deploy | + osism apply kubernetes-dashboard
deploy | WARNING: OSISM CLI should not be used as root user
deploy | 
deploy | 2024-07-22 08:41:50 | INFO     | Task cbd4d748-83e4-42fb-ba0f-45dad86becf6 (kubernetes-dashboard) was prepared for execution.
deploy | 2024-07-22 08:41:50 | INFO     | It takes a moment until task cbd4d748-83e4-42fb-ba0f-45dad86becf6 (kubernetes-dashboard) has been started and output is visible here.
deploy | + add_status error 'DEPLOY FAILED'
deploy | + local type=error
deploy | + local 'text=DEPLOY FAILED'
deploy | + '[' error = warn ']'
deploy | + '[' error = info ']'
deploy | + text='\e[5;41;1mERROR: DEPLOY FAILED\e[0m'
deploy | + [[ error = \i\n\f\o ]]
deploy | …
```

Get error output a bit more convenient

---

README.md
environments/configuration.yml
include.sh
init.sh

This change changes the ssh configuration to show the deployment status of CIAB directly after ssh login.
This change depends on https://github.com/osism/cloud-in-a-box/pull/306

Improve status display

---

README.md
init.sh

When selecting a branch different from "main" in the kernel-commandline a logic introduced a few weeks ago revokes the execution of run.sh.
```
bootstrap | + ./run.sh operator -e ansible_ssh_pass=password -e ansible_ssh_user=osism -e ansible_become_password=password
bootstrap | + set +x
ble-core~=2.16.5->ansible==9.4.0) (1.17.1)
bootstrap | Requirement already satisfied: pycparser in ./venv/lib/python3.10/site-packages (from cffi>=1.12->cryptography->ansible-core~=2.16.5->ansible==9.4.0) (2.22)
bootstrap | Installing collected packages: resolvelib, packaging, ansible-core, ansible
bootstrap | Successfully installed ansible-9.4.0 ansible-core-2.16.10 packaging-24.1 resolvelib-1.0.1
bootstrap | ERROR: Configured branch 'main' and current checkout-branch 'status_motd' are not the same! …
```

Branch logic

---

deploy.sh
environments/configuration.yml

It's not possible to uninstall cloud-init because cloud-init is still in use at this point.
Related to 07e6727a34fb1f188a5fc803de784a1bf518661d

Keep cloud-init, only disable it

---

Makefile
environments/manager/run.sh

Installations with uv are a lot faster than with pip.

Use uv instead of pip

---

include.sh

It's not mentioned in the docs.

Remove "Review the progress" notes

---

environments/configuration.yml

hosts_type = template is the default value in OSISM.

Remove hosts_type parameter

---

environments/kolla/files/overlays/nova/nova-compute.conf

Closes osism/cloud-in-a-box#238
Related to osism/issues#902

nova: set cpu_allocation_ratio = 3.0
