- environments/manager/playbook-operator.yml
- environments/manager/playbook-python.yml
- environments/manager/playbook-python3.yml
Partly osism/issues#232
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
> Change the place of the become condition

- README.md
- bootstrap.sh
- deploy.sh
- environments/manager/group_vars/manager.yml
- inventory/group_vars/generic/network.yml
> Remove cinder-volumes vg & support other network interface names

- deploy.sh
> Apply facts

- bootstrap.sh
> Restart the manager service

- deploy.sh
> Add missing wait_for_container_healthy

- deploy.sh
> Deploy netdata

- environments/manager/images.yml
Update the Ara Version in the file: /enviroments/manager/images.yml
> Change the Ara-Server Version to 1.6.1

- environments/kolla/configuration.yml
> kolla: remove defaults that are already in osism/ansible-defaults

- bootstrap.sh
> Add missing wait_for_container_healthy to bootstrap.sh

- bootstrap.sh
- environments/ansible.cfg
> Use redis cache for facts & gather facts before bootstrap

- environments/openstack/playbook-bootstrap.yml
> openstack: add bootstrap playbook

- environments/openstack/clouds.yml
- environments/openstack/secure.yml
> openstack: add octavia cloud definition

- deploy.sh
> Bootstrap openstack environment in deploy.sh

- bootstrap.sh
Fix ansible_ssh_user in the bootstrap.sh
> Fix default user

- environments/kolla/configuration.yml
Add the new om_enable_rabbitmq_high_availability variable
> Add neccessary new kolla option

- bootstrap.sh
- environments/manager/configuration.yml
- environments/manager/secrets.yml
The Netbox only makes sense in the context of Ironic. Therefore, it can be deactivated in the CiaB.
> manager: disable netbox service

- environments/openstack/playbook-bootstrap.yml
> Do not download the octavia amphora image

- environments/custom/templates/workarounds.sh.j2
> Escaped curly brakeds from interpretation via jinja2

- .zuul.yaml
> Zuul: Add yamllint check

- environments/kolla/configuration.yml
- environments/kolla/files/overlays/neutron.conf
Closes osism/cloud-in-a-box#69
> Set neutron availability zone

- environments/kolla/files/overlays/nova/nova-compute.conf
* reserve some host resources
* reduce overcommit
* start instances after reboot
> Add nova-compute configuration

- deploy.sh
- environments/kolla/configuration.yml
Closes osism/cloud-in-a-box#60
> Enable barbican deployment

- doc/quickstart.md
Also mention the use of the opesntack image manager.
> doc: overall improvements

- .ansible-lint
- contrib/ownca/create_ca.yml
- contrib/ownca/create_manager.yml
- contrib/ownca/create_wildcard.yml
- environments/openstack/playbook-bootstrap.yml
- requirements.yml
- Fix some lintingerrors after refactoring.
- Exclude only affected tasks where necessary.
- Partly osism/issues#496
> Ansible-lint: Refactor rules and noqas

- doc/quickstart.md
Closes osism/cloud-in-a-box#64
> doc: add upgrade script

- deploy.sh
- environments/ceph/configuration.yml
- environments/ceph/secrets.yml
- environments/openstack/playbook-bootstrap-ceph-rgw.yml
Closes osism/cloud-in-a-box#94
> Add swift endpoint

- doc/quickstart.md
Closes osism/cloud-in-a-box#106
> doc: add instructions for using a 2nd NIC for external network connectivity

- environments/ceph/configuration.yml
referencing https://github.com/osism/issues/issues/603
> removed deprecated rgw revocation param

- bootstrap.sh
- cleanup.sh
- deploy.sh
- prepare.sh
- upgrade.sh
With CLOUD_IN_A_BOX_TYPE it is possible to deploy different flavors of the Cloud in a Box. At the moment only the type sandbox is supported.
> Support CLOUD_IN_A_BOX_TYPE

- bootstrap.sh
- deploy.sh
- environments/openstack/playbook-bootstrap-edge.yml
- environments/openstack/playbook-bootstrap-sandbox.yml
Also uses OVN on the edge type because we do not have the resources for Amphora instances there.
> Allow different bootstrap plays for different types

- deploy.sh
> Do not use $HOME for $KUBECONFIG

- bootstrap.sh
- environments/configuration.yml
- releasenotes/notes/limits-0d83e2459227c47b.yaml
Closes osism/cloud-in-a-box#141
> Increase the number of open files

- deploy.sh
- releasenotes/notes/loadbalancer-ng-6bee4f64f8ada0b2.yaml
- upgrade.sh
This reverts commit d06d2ec2a367c2d44e96483ba0c46cd86cc2d9d5.
> Revert "Use loadbalancer-ng play to deploy the loadbalancer (#154)"

- deploy.sh
This way it is possible to use the scripts as normal user.
> Add missing sudo to lvcreate

- include.sh
This way it is possible to use the scripts as normal user.
> Add missing sudo to tee

- include.sh
- releasenotes/notes/add_status_does_not_exist-185-fd32807ebac65141.yaml
> Add status does not exist#181

- environments/openstack/playbook-bootstrap-edge.yml
- environments/openstack/playbook-bootstrap-sandbox.yml
Required by e88f4d9f54dcb0e0c7307c92b93f596c1487dc9c.
> openstack: create domain-manager role

- environments/openstack/playbook-test.yml
Required by e88f4d9f54dcb0e0c7307c92b93f596c1487dc9c.
> openstack: generate an OpenSSH keypair

- deploy.sh
- environments/ceph/configuration.yml
- releasenotes/notes/ceph-dashboard-internal-network-e7d44e38338b33fa.yaml
Closes osism/cloud-in-a-box#182
> Ceph dashboard now listens on 192.168.16.10:7000

- environments/openstack/playbook-bootstrap-sandbox.yml
Related to 8377fe46876c24152454b0da079a63e4a8af8bba
> openstack: remove amphora image

- upgrade.sh
This is now possible with the OSISM 7 release.
> Use osism update docker

- upgrade.sh
Related to b0df2ba9aefeb7fa824d0ff1a3d76f521ff21499
> Use plays to upgrade kubernetes & clusterapi

- environments/kolla/files/overlays/keystone/policy.yaml
- environments/openstack/playbook-bootstrap-edge.yml
- environments/openstack/playbook-bootstrap-sandbox.yml
- environments/openstack/playbook-test.yml
> Rename domain-manager to manager

- upgrade.sh
Related to 93f3e79b3711138448a9015bcbb60b8e5cf7dd0d
> Add missing copy-kubeconfig

- deploy.sh
- upgrade.sh
Makes the edge variant a little bit thinner.
> Do not deploy netdata & skyline on the edge

- deploy.sh
- inventory/group_vars/generic/ceph.yml
> Use ceph-pools play to create ceph pools

- bootstrap.sh
- deploy.sh
- init.sh
Also improve the scripts a little bit.
> Sync images when type = kubernetes

- init.sh
Related to d535dd5d76918dde167eb93a20b7b017aff7ac38
> Fix init.sh script

- environments/infrastructure/configuration.yml
- inventory/group_vars/generic/k3s.yml
Revert 10c1d782641fc0241d6f7166399ba9ac8e825fcd
> k3s: back to flannel for the moment

- deploy.sh
> Rename kubernetes-dashboard -> k8s-dashboard

- environments/infrastructure/configuration.yml
- environments/manager/configuration.yml
Only plugins that have been activated by default should be used.
Closes osism/issues#1136
> Do not use extra netbox plugins

- deploy.sh
- environments/kolla/configuration.yml
- upgrade.sh
> Disable ironic by default

- environments/manager/configuration.yml
Related to osism/cloud-in-a-box#317
> manager: set netbox start period to 240s

- environments/configuration.yml
enable_auditd is set to false by default.
> Remove enable_auditd parameter

- bootstrap.sh
- deploy.sh
> Disable cloud-init network configuration

- bootstrap.sh
- deploy.sh
ARA makes Ansible pretty slow. Disable ARA for the initial deployment and only use if for upgrades & manual steps.
> Disable ARA

- bootstrap.sh
Related to f3fe776189c95fc844550332761bf6ea9990b095.
> Fix path to disable-ara.sh script

- environments/generic/configuration.yml
The parameter are part of the osism/defaults repository.
> Remove dotfiles parameters

- environments/custom/playbook-workarounds.yml
- environments/custom/templates/shutdown-instances.service.j2
- environments/custom/templates/shutdown-instances.sh.j2
Closes osism/cloud-in-a-box#262
> custom: add service to shutdown instances before system shutdown

- environments/infrastructure/configuration.yml
- environments/kolla/configuration.yml
- include.sh
- prepare.sh
Related to osism/cloud-in-a-box#336
> Make bind/designate usable via wireguard

- bootstrap.sh
- environments/kolla/configuration.yml
Related to 26c078d3165d857aa2fb455e1b70f6ecde228c6a.
> Fix "Make bind/designate usable via wireguard"
